js2
htmlacademy-ecmascript/908335-cinemaddict-14 pull request #4
Opened 2021-04-06 11:40 UTC by Evafan1337

create basic app

2021-04-06 13:07 UTC, ademaro commented
@Evafan1337 делай, плиз, нормальные названия коммитов, что бы было понятно что там. И не один гигантский, а разбивай на конкретные задачи: 1. Сделаны моки для генерации фильмов, 2. Переделан компонент для показа реальных данных и тд...

2021-04-06 13:29 UTC, ademaro requested changes
Жду поправок, ПР пока открытым оставляю

2021-04-06 13:29 UTC, ademaro commented on src/main.js
>   * Функция рендера компонента
Эту ф-цию уже в utils.js, например, можем перенести

2021-04-06 13:29 UTC, ademaro commented on src/main.js
> +const compareValues = (key, order) => {
сортировку по-умолчанию можно сделать (`order = 'asc'`)

2021-04-06 13:29 UTC, ademaro commented on src/main.js
> +let filteredFilms = films.sort(compareValues(`id`, `asc`));
Зачем вообще тут сортируем?)

2021-04-06 13:29 UTC, ademaro commented on src/main.js
> +const filmsRated = () => {
Давай не из внешней области видимости брать, давай параметризируем

2021-04-06 13:29 UTC, ademaro commented on src/main.js
> +siteBody.addEventListener(`click`, function (event) {
нам разве везде бектики надо использовать? Может, для обычных строк — одинарные кавычки, а для строк с интерполяцией — в бектиках?

2021-04-06 13:29 UTC, ademaro commented on src/mock/comments.js
> +import {getRandomInteger} from "./random";
тут вообще и одинарные и двойные кавычки...

2021-04-06 13:29 UTC, ademaro commented on src/mock/comments.js
> +  const comments = [
Сделай это через цикл + параметризируй количество комментов для генерации

2021-04-06 13:29 UTC, ademaro commented on src/mock/comments.js
> +    info: generateComment(),
может, упростим структуру? зачем поле info тебе?
```js
{
  id: <str>,
  text: <str>,
  author: <str>,
  emotion: <str>,
  date: <datetime>
}
```

2021-04-06 13:29 UTC, ademaro commented on src/mock/film.js
> +  const info = [
пересмотри и эту ф-цию...

2021-04-06 13:29 UTC, ademaro commented on src/mock/film.js
> +  `Alfred Hitchcock`,
Это константы, КАПСОМ давай их сразу

2021-04-06 13:29 UTC, ademaro commented on src/mock/film.js
> +  return randomHour + `h ` + randomMinutes + `m`;
Если используешь интерполяцию, то конкатенация не нужна

2021-04-06 13:29 UTC, ademaro commented on src/mock/film.js
> +const regisseurs = [
directors или producers, наверное?)

2021-04-06 13:29 UTC, ademaro commented on src/mock/film.js
> +    actors: choise(actors, getRandomInteger(1, actors.length - 1)),
У тебя могут генерироваться одни и те же актёры)) Попробуй сделать ф-цию:
1. берём массив-донор
2. перемешиваем
3. обрезаем его от 1 до arr.length элементов

2021-04-06 13:29 UTC, ademaro commented on src/mock/random.js
> +/**
сделай, может, mocks/utils.js для вспомогательных ф-ций создания тестовых данных

2021-04-06 13:29 UTC, ademaro commented on src/view/comments.js
> +const emoji = (emotion) => {
бесполезная ф-ция, она подставляет `.png` к любой иконке, просто добавь это в шаблон. Если новая иконка появится, то тебе придётся делать ещё пункт?))

2021-04-07 22:07 UTC, Evafan1337 commented on src/main.js
>   * Функция рендера компонента
+

2021-04-07 22:24 UTC, Evafan1337 commented on src/main.js
> +let filteredFilms = films.sort(compareValues(`id`, `asc`));
Так сортировка по умолчанию? Не понял заметки

2021-04-07 22:29 UTC, Evafan1337 commented on src/mock/film.js
> +  `Alfred Hitchcock`,
+

2021-04-07 22:29 UTC, Evafan1337 commented on src/mock/random.js
> +/**
+

2021-04-07 22:29 UTC, Evafan1337 commented on src/view/comments.js
> +const emoji = (emotion) => {
+

2021-04-07 22:33 UTC, Evafan1337 commented on src/mock/comments.js
> +    info: generateComment(),
Хранить информацию о комментариях, предлагаешь хранить сразу полями, избегая поля info?

2021-04-11 13:43 UTC, ademaro commented on src/main.js
> +siteBody.addEventListener(`click`, function (event) {
event — переименовываем

2021-04-11 14:02 UTC, ademaro approved these changes

2021-04-11 14:02 UTC, merged